package com.media;

import java.io.File;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;

import com.winterwell.utils.Proc;
import com.winterwell.utils.Utils;
import com.winterwell.utils.containers.ArrayMap;
import com.winterwell.utils.log.Log;

public class FileProcessor {
	
	public static final String STANDARD_RES_QUALITY = "800";
	public static final String LOW_RES_QUALITY = "360";
	
	public File rawDest;
	public File standardDest;
	public File mobileDest;
	public final List<String> commands;
	
	private FileProcessor(File rawDest, File standardDest, File mobileDest, List<String> commands) {
		this.rawDest = rawDest;
		// Moderately compressed version. Generated by either doProcessImage or doProcessVideo
		this.standardDest = standardDest;
		// Most compressed version. Generated by either doProcessImage or doProcessVideo
		this.mobileDest = mobileDest;
		
		this.commands = commands;
	}
	
	public static FileProcessor ImageProcessor(File rawDest, File standardDest, File mobileDest) {
		String inputImagePath = rawDest.getAbsolutePath();
		String standardImagePath = standardDest.getAbsolutePath();
		String lowResImagePath = mobileDest.getAbsolutePath();
		
		String command = "magick " + inputImagePath + " -resize " + STANDARD_RES_QUALITY + " " + standardImagePath
		+ "; " + "magick " + inputImagePath + " -resize " + LOW_RES_QUALITY + " " + lowResImagePath;
		List<String> commands = Arrays.asList("/bin/bash", "-c", command);
		
		return new FileProcessor(rawDest, standardDest, mobileDest, commands);
	}

	public static FileProcessor VideoProcessor(File rawDest, File standardDest, File mobileDest) {
		String inputVideoPath = rawDest.getAbsolutePath();
		String lowResVideoPath = mobileDest.getAbsolutePath();
		String highResVideoPath = standardDest.getAbsolutePath();
		
		String command = "HandBrakeCLI " + "--input " + inputVideoPath + " --preset 'Gmail Medium 5 Minutes 480p30' " + "--output " + lowResVideoPath
		+ "; " + "HandBrakeCLI " + "--input " + inputVideoPath + " --preset 'Gmail Large 3 Minutes 720p30' " + "--output " + highResVideoPath;
		List<String> commands = Arrays.asList("/bin/bash", "-c", command);
		
		return new FileProcessor(rawDest, standardDest, mobileDest, commands);
	}
	
	/** Perform the given conversion operation 
	 *  Need to provide pool of threads to run from **/
	public Map run(ExecutorService pool) {
		pool.submit(() -> {
				Proc process = new Proc(this.commands);
			try {
				process.start();
				process.waitFor();
				Log.d(process.getOutput());
				if ( ! Utils.isBlank(process.getError())) {
					Log.e(process.getError());
				}
			} catch (Throwable e) {
				Log.e(e);
			}
		});
		
		Map out = new ArrayMap();
		out.put("raw", this.rawDest);		
		out.put("standard", this.standardDest);
		out.put("mobile", this.mobileDest);
		return out;
	}
}